spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: "public"
  datasource:
    url: jdbc:postgresql://localhost:35432/paketomat
    username: paketomatuser
    password: s3creT
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: centerpaketomat@gmail.com
    password: sidgklovbikxivmt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  cache:
    cache-names: rate-limit-buckets
    caffeine:
      spec: maximumSize=100000, expireAfterAccess=3600s

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: "https://countries-cities.p.rapidapi.com/location/country/RS/city/list?page=2&per_page=100&population=1501"
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
          bandwidths:
            - capacity: 1
              time: 2
              unit: seconds

external.api.city:
  start-page: 1
  url: "https://countries-cities.p.rapidapi.com/location/country/RS/city/list?page={1}&per_page=100&population=1501"
  header:
    key:
      name: "X-RapidAPI-Key"
      value: "c427cbdd50msh072fe84a375af9cp1f2596jsn0f5919dacf12"
    host:
      name: "X-RapidAPI-Host"
      value: "countries-cities.p.rapidapi.com"

external.api.distance:
  url: "https://distanceto.p.rapidapi.com/get?route=[{\"t\":\"{cityReciever}\"},{\"t\":\"{cityPaketomat}\"}]&car=false"
  header:
    key:
      name: "X-RapidAPI-Key"
      value: "c427cbdd50msh072fe84a375af9cp1f2596jsn0f5919dacf12"
    host:
      name: "X-RapidAPI-Host"
      value: "distanceto.p.rapidapi.com"

paketomat:
  min-population : 10000
  size-of-paketomat: 5

dispatcher:
  distance : "haversine"

