spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:35432/paketomat
    username: paketomatuser
    password: s3creT
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: centerpaketomat@gmail.com
    password: sidgklovbikxivmt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

external.api.city:
  start-page: 1
  url: "https://countries-cities.p.rapidapi.com/location/country/RS/city/list?page={1}&per_page=100&population=1501"
  header:
    key:
      name: "X-RapidAPI-Key"
      value: "c427cbdd50msh072fe84a375af9cp1f2596jsn0f5919dacf12"
    host:
      name: "X-RapidAPI-Host"
      value: "countries-cities.p.rapidapi.com"

external.api.distance:
  url: "https://distanceto.p.rapidapi.com/get?route=[{\"t\":\"{cityReciever}\"},{\"t\":\"{cityPaketomat}\"}]&car=false"
  header:
    key:
      name: "X-RapidAPI-Key"
      value: "c427cbdd50msh072fe84a375af9cp1f2596jsn0f5919dacf12"
    host:
      name: "X-RapidAPI-Host"
      value: "distanceto.p.rapidapi.com"

paketomat:
  min-population : 10000
  size-of-paketomat: 5



