spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:35432/paketomat
    username: paketomatuser
    password: s3creT
    driverClassName: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: gligorijevicdusan6@gmail.com
    password: mbwdovaqekjaglhc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
